import yaml

from snakemake.utils import min_version, validate

min_version("9.19")


# !!!!! IMPORTANT !!!!!
# Define pathvars for all user resource files and result files
# This allows users to re-wire how the module is used in their workflow with ease.
pathvars:
    shapes="<resources>/user/{shapes}/shapes.parquet",
    floor_area="<results>/{shapes}/rasters/floor_area.tif",
    residential_space_heat_weight="<results>/{shapes}/rasters/residential_space_heat_weight.tif",


# Load the example configuration. This will be overridden by users.
configfile: workflow.source_path("../config/config.yaml")


# Validate the configuration using the schema file.
validate(config, workflow.source_path("internal/config.schema.yaml"))

# Load internal settings separately so users cannot modify them.
with open(workflow.source_path("internal/settings.yaml"), "r") as f:
    internal = yaml.safe_load(f)


# Add all your includes here.
include: "rules/_utils.smk"
include: "rules/automatic.smk"
include: "rules/prepare.smk"
include: "rules/floor_area.smk"
include: "rules/space_heat_weight.smk"


# Add additional files to be delivered alongside the workflow here.
# This is needed e.g. for python code files that are never
# explicitly used as a script or input in a snakemake rule.
workflow.source_path("scripts/_schemas.py")
workflow.source_path("scripts/_raster.py")
workflow.source_path("scripts/_plots.py")
workflow.source_path("scripts/_eubucco.py")
workflow.source_path("scripts/_floor_area.py")
workflow.source_path("scripts/_microsoft.py")
workflow.source_path("scripts/_regions.py")
workflow.source_path("scripts/_space_heat_weight.py")


rule all:
    default_target: True
    output:
        "INVALID",
    log:
        stderr="<logs>/all.stderr",
    conda:
        "envs/module.yaml"
    message:
        "ERROR: Invalid `rule all:` call"
    shell:
        'echo "This workflow must be called as a snakemake module." > {log.stderr}'
