# Changes here will be overwritten by Copier
# !!!!! DO NOT MANUALLY MODIFY THIS FILE !!!!!
_commit: v1.0.3
_src_path: https://github.com/modelblocks-org/data-module-template.git
authors:
-   email: y.f.egberink@tudelft.nl
    family_name: Egberink
    given_name: Yannick
github_org: modelblocks-org
license: Apache-2.0
maintainers:
-   email: y.f.egberink@tudelft.nl
    family_name: Egberink
    given_name: Yannick
module_code_name: module_district_heating
module_description: In this module district heating potentials and costs are calculated
    using the approach from Fallahnejad et al. 2024.
module_human_name: District heating potential and cost
